# Generated by Django 3.2.9 on 2021-11-29 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('name', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('desc', models.CharField(max_length=137)),
            ],
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('name', models.CharField(max_length=27, primary_key=True, serialize=False)),
                ('m_type', models.CharField(max_length=8)),
                ('category', models.CharField(max_length=8)),
                ('power', models.FloatField()),
                ('accuracy', models.FloatField()),
                ('pp', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.IntegerField()),
                ('pokedex_no', models.IntegerField(unique=True)),
                ('pokedex_entry', models.CharField(max_length=218)),
                ('name', models.CharField(max_length=17, unique=True)),
                ('weight', models.CharField(max_length=21)),
                ('height', models.CharField(max_length=15)),
                ('generation', models.IntegerField()),
            ],
            options={
                'unique_together': {('pokedex_no', 'name')},
            },
        ),
        migrations.CreateModel(
            name='pokeMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move', models.CharField(max_length=16)),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemondb.pokemon', to_field='name')),
            ],
        ),
        migrations.CreateModel(
            name='pokeAbility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ability', models.CharField(max_length=16)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemondb.pokemon', to_field='name')),
            ],
        ),
        migrations.CreateModel(
            name='appearance',
            fields=[
                ('types', models.CharField(max_length=23)),
                ('picture', models.CharField(max_length=66)),
                ('appearance_id', models.IntegerField(primary_key=True, serialize=False)),
                ('form', models.CharField(max_length=22)),
                ('unique_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemondb.pokemon', to_field='pokedex_no')),
            ],
        ),
    ]
