# Generated by Django 3.2.9 on 2021-11-29 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemondb', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ability',
            old_name='desc',
            new_name='description',
        ),
    ]
