# Generated by Django 3.2.9 on 2021-11-29 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemondb', '0002_rename_desc_ability_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='move',
            name='accuracy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='move',
            name='category',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='move',
            name='power',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='move',
            name='pp',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
