# Generated by Django 3.2.9 on 2021-11-29 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemondb', '0004_rename_unique_id_appearance_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemove',
            name='move',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
