# Generated by Django 3.2.9 on 2021-11-30 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemondb', '0005_alter_pokemove_move'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appearance',
            old_name='unique',
            new_name='uniques',
        ),
    ]
